// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0pb_hXI1AfInI6i7I0iPCy6Cf2DiwnfI',
    appId: '1:356654785605:web:8a15b4e1148fd44eb42f2c',
    messagingSenderId: '356654785605',
    projectId: 'menuapp06',
    authDomain: 'menuapp06.firebaseapp.com',
    databaseURL: 'https://menuapp06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'menuapp06.firebasestorage.app',
    measurementId: 'G-5BXX3F07XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOpzJbZMU20DbBN-ur62OzKejalVF39dM',
    appId: '1:356654785605:android:0f5ae663f67dc723b42f2c',
    messagingSenderId: '356654785605',
    projectId: 'menuapp06',
    databaseURL: 'https://menuapp06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'menuapp06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HL7wdkI_ehw2FOdiwpJcZEaxGuRnNxs',
    appId: '1:356654785605:ios:9d0f0d2fd5d75ddcb42f2c',
    messagingSenderId: '356654785605',
    projectId: 'menuapp06',
    databaseURL: 'https://menuapp06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'menuapp06.firebasestorage.app',
    iosBundleId: 'com.example.apiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HL7wdkI_ehw2FOdiwpJcZEaxGuRnNxs',
    appId: '1:356654785605:ios:9d0f0d2fd5d75ddcb42f2c',
    messagingSenderId: '356654785605',
    projectId: 'menuapp06',
    databaseURL: 'https://menuapp06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'menuapp06.firebasestorage.app',
    iosBundleId: 'com.example.apiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0pb_hXI1AfInI6i7I0iPCy6Cf2DiwnfI',
    appId: '1:356654785605:web:cd96ed81bd793898b42f2c',
    messagingSenderId: '356654785605',
    projectId: 'menuapp06',
    authDomain: 'menuapp06.firebaseapp.com',
    databaseURL: 'https://menuapp06-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'menuapp06.firebasestorage.app',
    measurementId: 'G-B64JD5HJW3',
  );

}